version: '3.8'

services:
  sonar:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"  
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar  
      - SONARQUBE_JDBC_USERNAME=sonar  
      - SONARQUBE_JDBC_PASSWORD=sonar  
    volumes:
      - sonar-data:/opt/sonarqube/data  
      - sonar-logs:/opt/sonarqube/logs  
      - sonar-extensions:/opt/sonarqube/extensions  
    networks:
      - sonar-network 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 10s

  postgres:
    image: postgres:16.4-alpine3.20
    container_name: postgres
    environment:
      - POSTGRES_USER=sonar  
      - POSTGRES_PASSWORD=sonar  
      - POSTGRES_DB=sonar  
    volumes:
      - postgres-data:/var/lib/postgresql/data  
    networks:
      - sonar-network  
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sonar"]
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 10s

volumes:
  sonar-data:
  sonar-logs:
  sonar-extensions:
  postgres-data:

networks:
  sonar-network:
    driver: bridge
